version = 0.1

[default]
[default.global.parameters]
stack_name = "penny-expense-processor"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
resolve_image_repos = true
region = "us-east-2"

parameter_overrides = [
    "ProcessingQueueArn=arn:aws:sqs:us-east-2:872098897244:penny-expense-processing-queue",
    "TelegramBotToken=TOKEN",
    "GoogleSheetId=TOKEN",
    "GoogleServiceAccountSecret=penny-expense-google-service-account",
    "GeminiApiKey=TOKEN",
]

[default.local_invoke.parameters]
parameter_overrides = [
    "TelegramBotToken=TOKEN",
    "GoogleSheetId=TOKEN",
    "GoogleServiceAccountSecret=penny-expense-google-service-account"
]
